#!/usr/bin/env python3
"""PaperPass real upload/parse flow.

This script only calls observed PaperPass endpoints and saves raw responses.
It does not bypass Tencent captcha, login, or payment. A real final report is
available only after the official site submission flow completes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import os
from datetime import datetime
from pathlib import Path

import requests


BASE = "https://www.paperpass.com"


def now_id() -> str:
    return datetime.now().strftime("%Y%m%d-%H%M%S")


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", required=True, help="DOC/DOCX/PDF manuscript path")
    parser.add_argument("--out-dir", default="domestic_detection/runs")
    args = parser.parse_args()

    manuscript = Path(args.file).expanduser().resolve()
    if not manuscript.exists():
        raise SystemExit(f"missing manuscript: {manuscript}")

    ext = manuscript.suffix.lower().lstrip(".")
    if ext not in {"doc", "docx", "pdf"}:
        raise SystemExit("PaperPass upload page accepts only .doc, .docx, .pdf for this flow")
    if manuscript.stat().st_size >= 30 * 1024 * 1024:
        raise SystemExit("PaperPass upload limit is 30 MB")

    run_dir = Path(args.out_dir).resolve() / f"paperpass-{now_id()}"
    run_dir.mkdir(parents=True, exist_ok=True)

    sess = requests.Session()
    sess.headers.update(
        {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/537.36 Chrome Safari/537.36",
            "Referer": f"{BASE}/upload",
            "Origin": BASE,
            "X-Requested-With": "XMLHttpRequest",
        }
    )

    landing = sess.get(f"{BASE}/upload", timeout=30)
    (run_dir / "00-upload-page.html").write_text(landing.text, encoding="utf-8", errors="ignore")
    landing.raise_for_status()

    sign_resp = sess.post(
        f"{BASE}/api/paper/get-upload-sign",
        data={"ext": ext, "title": manuscript.name, "file_size": manuscript.stat().st_size},
        timeout=30,
    )
    sign_text = sign_resp.text
    (run_dir / "01-get-upload-sign.raw").write_text(sign_text, encoding="utf-8", errors="ignore")
    sign_resp.raise_for_status()
    sign = sign_resp.json()
    write_json(run_dir / "01-get-upload-sign.json", sign)
    if sign.get("code") != 0:
        raise SystemExit(f"PaperPass sign failed, see {run_dir / '01-get-upload-sign.json'}")
    data = sign["data"]

    mime = mimetypes.guess_type(manuscript.name)[0] or "application/octet-stream"
    with manuscript.open("rb") as f:
        files = {"file": (manuscript.name, f, mime)}
        form = {
            "key": data["object_key"],
            "policy": data["policy"],
            "success_action_status": "200",
            "x-oss-signature-version": data["signature_version"],
            "x-oss-credential": data["credential"],
            "x-oss-date": data["date"],
            "Content-Disposition": "attachment;filename="
            + manuscript.name
            + ";filename*=utf-8''"
            + requests.utils.quote(manuscript.name),
            "x-oss-signature": data["signature"],
        }
        oss_resp = sess.post(data["end_point"], data=form, files=files, timeout=120)
    (run_dir / "02-oss-upload-status.txt").write_text(
        f"status={oss_resp.status_code}\nheaders={dict(oss_resp.headers)}\nbody={oss_resp.text[:1000]}",
        encoding="utf-8",
    )
    if oss_resp.status_code not in {200, 201, 204}:
        raise SystemExit(f"OSS upload failed, see {run_dir / '02-oss-upload-status.txt'}")

    parse_resp = sess.post(
        f"{BASE}/api/paper/parse",
        data={"key": data["file_key"], "method": "sign"},
        timeout=120,
    )
    (run_dir / "03-parse.raw").write_text(parse_resp.text, encoding="utf-8", errors="ignore")
    parse_resp.raise_for_status()
    parsed = parse_resp.json()
    write_json(run_dir / "03-parse.json", parsed)

    summary = {
        "service": "PaperPass",
        "base_url": BASE,
        "file": str(manuscript),
        "sha256": sha256_file(manuscript),
        "run_dir": str(run_dir),
        "status": "uploaded_and_parsed" if parsed.get("status") == 0 else "parse_failed",
        "next_step": "Open https://www.paperpass.com/upload or /panel/index with the same browser session and complete official captcha/payment/submission. No final report has been generated by this script.",
        "raw_files": [
            "00-upload-page.html",
            "01-get-upload-sign.json",
            "02-oss-upload-status.txt",
            "03-parse.json",
        ],
    }
    write_json(run_dir / "summary.json", summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
